<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@yield('title')</title>
    <link href="/css/variables.css" rel="stylesheet" />
    <link href="/css/layout/main.css" rel="stylesheet" />
    <link href="/css/layout/navbar.css" rel="stylesheet" />
</head>

<body>
    @include('layouts.navbar')
    <div id="content-container">
        <main>
            Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam erat volutpat. Nulla quis diam. Aenean fermentum risus id tortor. Duis viverra diam non justo. Nulla est. Curabitur sagittis hendrerit ante. Fusce tellus odio, dapibus id fermentum quis, suscipit id erat. Nulla turpis magna, cursus sit amet, suscipit a, interdum id, felis. Aliquam ante. Integer pellentesque quam vel velit. Etiam posuere lacus quis dolor. Fusce suscipit libero eget elit. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Proin mattis lacinia justo. Praesent vitae arcu tempor neque lacinia pretium. Nam quis nulla.

            Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Aliquam erat volutpat. Etiam neque. Etiam sapien elit, consequat eget, tristique non, venenatis quis, ante. Maecenas sollicitudin. Maecenas ipsum velit, consectetuer eu lobortis ut, dictum at dui. Pellentesque sapien. Fusce tellus odio, dapibus id fermentum quis, suscipit id erat. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat. Duis viverra diam non justo. Duis pulvinar. Aenean fermentum risus id tortor. Praesent vitae arcu tempor neque lacinia pretium. Nullam dapibus fermentum ipsum. Aliquam erat volutpat. Duis condimentum augue id magna semper rutrum.

            Phasellus enim erat, vestibulum vel, aliquam a, posuere eu, velit. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Vestibulum fermentum tortor id mi. Nulla turpis magna, cursus sit amet, suscipit a, interdum id, felis. Aliquam erat volutpat. Duis condimentum augue id magna semper rutrum. Suspendisse nisl. Vivamus ac leo pretium faucibus. Aliquam erat volutpat. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Phasellus rhoncus. Fusce wisi. Aenean vel massa quis mauris vehicula lacinia.

            Quisque tincidunt scelerisque libero. Nunc tincidunt ante vitae massa. Nullam at arcu a est sollicitudin euismod. Nulla quis diam. Pellentesque pretium lectus id turpis. Nullam eget nisl. Vivamus ac leo pretium faucibus. Praesent in mauris eu tortor porttitor accumsan. Et harum quidem rerum facilis est et expedita distinctio. Morbi imperdiet, mauris ac auctor dictum, nisl ligula egestas nulla, et sollicitudin sem purus in lacus. Sed convallis magna eu sem. Nullam justo enim, consectetuer nec, ullamcorper ac, vestibulum in, elit. Sed ac dolor sit amet purus malesuada congue. Integer malesuada.
            Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam erat volutpat. Nulla quis diam. Aenean fermentum risus id tortor. Duis viverra diam non justo. Nulla est. Curabitur sagittis hendrerit ante. Fusce tellus odio, dapibus id fermentum quis, suscipit id erat. Nulla turpis magna, cursus sit amet, suscipit a, interdum id, felis. Aliquam ante. Integer pellentesque quam vel velit. Etiam posuere lacus quis dolor. Fusce suscipit libero eget elit. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Proin mattis lacinia justo. Praesent vitae arcu tempor neque lacinia pretium. Nam quis nulla.

            Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Aliquam erat volutpat. Etiam neque. Etiam sapien elit, consequat eget, tristique non, venenatis quis, ante. Maecenas sollicitudin. Maecenas ipsum velit, consectetuer eu lobortis ut, dictum at dui. Pellentesque sapien. Fusce tellus odio, dapibus id fermentum quis, suscipit id erat. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat. Duis viverra diam non justo. Duis pulvinar. Aenean fermentum risus id tortor. Praesent vitae arcu tempor neque lacinia pretium. Nullam dapibus fermentum ipsum. Aliquam erat volutpat. Duis condimentum augue id magna semper rutrum.

            Phasellus enim erat, vestibulum vel, aliquam a, posuere eu, velit. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Vestibulum fermentum tortor id mi. Nulla turpis magna, cursus sit amet, suscipit a, interdum id, felis. Aliquam erat volutpat. Duis condimentum augue id magna semper rutrum. Suspendisse nisl. Vivamus ac leo pretium faucibus. Aliquam erat volutpat. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Phasellus rhoncus. Fusce wisi. Aenean vel massa quis mauris vehicula lacinia.

            Quisque tincidunt scelerisque libero. Nunc tincidunt ante vitae massa. Nullam at arcu a est sollicitudin euismod. Nulla quis diam. Pellentesque pretium lectus id turpis. Nullam eget nisl. Vivamus ac leo pretium faucibus. Praesent in mauris eu tortor porttitor accumsan. Et harum quidem rerum facilis est et expedita distinctio. Morbi imperdiet, mauris ac auctor dictum, nisl ligula egestas nulla, et sollicitudin sem purus in lacus. Sed convallis magna eu sem. Nullam justo enim, consectetuer nec, ullamcorper ac, vestibulum in, elit. Sed ac dolor sit amet purus malesuada congue. Integer malesuada.
            Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam erat volutpat. Nulla quis diam. Aenean fermentum risus id tortor. Duis viverra diam non justo. Nulla est. Curabitur sagittis hendrerit ante. Fusce tellus odio, dapibus id fermentum quis, suscipit id erat. Nulla turpis magna, cursus sit amet, suscipit a, interdum id, felis. Aliquam ante. Integer pellentesque quam vel velit. Etiam posuere lacus quis dolor. Fusce suscipit libero eget elit. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Proin mattis lacinia justo. Praesent vitae arcu tempor neque lacinia pretium. Nam quis nulla.

            Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Aliquam erat volutpat. Etiam neque. Etiam sapien elit, consequat eget, tristique non, venenatis quis, ante. Maecenas sollicitudin. Maecenas ipsum velit, consectetuer eu lobortis ut, dictum at dui. Pellentesque sapien. Fusce tellus odio, dapibus id fermentum quis, suscipit id erat. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat. Duis viverra diam non justo. Duis pulvinar. Aenean fermentum risus id tortor. Praesent vitae arcu tempor neque lacinia pretium. Nullam dapibus fermentum ipsum. Aliquam erat volutpat. Duis condimentum augue id magna semper rutrum.

            Phasellus enim erat, vestibulum vel, aliquam a, posuere eu, velit. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Vestibulum fermentum tortor id mi. Nulla turpis magna, cursus sit amet, suscipit a, interdum id, felis. Aliquam erat volutpat. Duis condimentum augue id magna semper rutrum. Suspendisse nisl. Vivamus ac leo pretium faucibus. Aliquam erat volutpat. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Phasellus rhoncus. Fusce wisi. Aenean vel massa quis mauris vehicula lacinia.

            Quisque tincidunt scelerisque libero. Nunc tincidunt ante vitae massa. Nullam at arcu a est sollicitudin euismod. Nulla quis diam. Pellentesque pretium lectus id turpis. Nullam eget nisl. Vivamus ac leo pretium faucibus. Praesent in mauris eu tortor porttitor accumsan. Et harum quidem rerum facilis est et expedita distinctio. Morbi imperdiet, mauris ac auctor dictum, nisl ligula egestas nulla, et sollicitudin sem purus in lacus. Sed convallis magna eu sem. Nullam justo enim, consectetuer nec, ullamcorper ac, vestibulum in, elit. Sed ac dolor sit amet purus malesuada congue. Integer malesuada.

        </main>
        @include('layouts.footer')
    </div>
    <script src="/js/navbar.js"></script>
</body>

</html>